export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS";
export const CREATE_RESERVATION_FAIL = "CREATE_RESERVATION_FAIL";

export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_FAIL = "GET_RESERVATIONS_FAIL";
export const GET_RECEIVED_CONTRACTS_REQUEST = 'GET_RECEIVED_CONTRACTS_REQUEST';
export const GET_RECEIVED_CONTRACTS_SUCCESS = 'GET_RECEIVED_CONTRACTS_SUCCESS';
export const GET_RECEIVED_CONTRACTS_FAIL = 'GET_RECEIVED_CONTRACTS_FAIL';

export const VALIDATE_CONTRACT_REQUEST = 'VALIDATE_CONTRACT_REQUEST';
export const VALIDATE_CONTRACT_SUCCESS = 'VALIDATE_CONTRACT_SUCCESS';
export const VALIDATE_CONTRACT_FAIL = 'VALIDATE_CONTRACT_FAIL';

export const SIGN_CONTRACT_REQUEST = 'SIGN_CONTRACT_REQUEST';
export const SIGN_CONTRACT_SUCCESS = 'SIGN_CONTRACT_SUCCESS';
export const SIGN_CONTRACT_FAIL = 'SIGN_CONTRACT_FAIL';

export const CONTRACT_STATUS = {
  PENDING: 'EN_ATTENTE',
  ACTIVE: 'ACTIF',
  REFUSED: 'REFUSÉ',
  EXPIRED: 'EXPIRÉ',
  ALL: 'TOUS'
};